In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv("../input/fetalhr/CTG.csv")

In [3]:
df.head()

FileName       Date      SegFile      b       e    LBE     LB   AC  \
0  Variab10.txt  12/1/1996  CTG0001.txt  240.0   357.0  120.0  120.0  0.0   
1    Fmcs_1.txt   5/3/1996  CTG0002.txt    5.0   632.0  132.0  132.0  4.0   
2    Fmcs_1.txt   5/3/1996  CTG0003.txt  177.0   779.0  133.0  133.0  2.0   
3    Fmcs_1.txt   5/3/1996  CTG0004.txt  411.0  1192.0  134.0  134.0  2.0   
4    Fmcs_1.txt   5/3/1996  CTG0005.txt  533.0  1147.0  132.0  132.0  4.0   

    FM   UC  ...    C    D    E   AD   DE   LD   FS  SUSP  CLASS  NSP  
0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0   0.0    9.0  2.0  
1  0.0  4.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
2  0.0  5.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
3  0.0  6.0  ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
4  0.0  5.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0    2.0  1.0  

[5 rows x 40 columns]

## FileName:	of CTG examination	
## Date:	of the examination	
## b:	start instant	
## e:	end instant	
## LBE:	baseline value (medical expert)	
## LB:	baseline value (SisPorto)	
## AC:	accelerations (SisPorto)	
## FM:	foetal movement (SisPorto)	
## UC:	uterine contractions (SisPorto)	
## ASTV:	percentage of time with abnormal short term variability  (SisPorto)	
## mSTV:	mean value of short term variability  (SisPorto)	
## ALTV:	percentage of time with abnormal long term variability  (SisPorto)	
## mLTV:	mean value of long term variability  (SisPorto)	
## DL:	light decelerations	
## DS:	severe decelerations	
## DP:	prolongued decelerations	
## DR:	repetitive decelerations	
## Width:	histogram width	
## Min:	low freq. of the histogram	
## Max:	high freq. of the histogram	
## Nmax:	number of histogram peaks	
## Nzeros:	number of histogram zeros	
## Mode:	histogram mode	
## Mean:	histogram mean	
## Median:	histogram median	
## Variance:	histogram variance	
## Tendency:	histogram tendency: -1=left assymetric; 0=symmetric; 1=right assymetric	
## A:	calm sleep	
## B:	REM sleep	
## C:	calm vigilance	
## D:	active vigilance	
## SH:	shift pattern (A or Susp with shifts)	
## AD:	accelerative/decelerative pattern (stress situation)	
## DE:	decelerative pattern (vagal stimulation)	
## LD:	largely decelerative pattern	
## FS:	flat-sinusoidal pattern (pathological state)	
## SUSP:	suspect pattern	
## CLASS:	Class code (1 to 10) for classes A to SUSP	
## NSP:	Normal=1; Suspect=2; Pathologic=3	


In [4]:
df=df.drop(["FileName","Date","SegFile","b","e"],axis=1)

In [5]:
df.head()

LBE     LB   AC   FM   UC  ASTV  MSTV  ALTV  MLTV   DL  ...    C    D  \
0  120.0  120.0  0.0  0.0  0.0  73.0   0.5  43.0   2.4  0.0  ...  0.0  0.0   
1  132.0  132.0  4.0  0.0  4.0  17.0   2.1   0.0  10.4  2.0  ...  0.0  0.0   
2  133.0  133.0  2.0  0.0  5.0  16.0   2.1   0.0  13.4  2.0  ...  0.0  0.0   
3  134.0  134.0  2.0  0.0  6.0  16.0   2.4   0.0  23.0  2.0  ...  0.0  0.0   
4  132.0  132.0  4.0  0.0  5.0  16.0   2.4   0.0  19.9  0.0  ...  0.0  0.0   

     E   AD   DE   LD   FS  SUSP  CLASS  NSP  
0  0.0  0.0  0.0  0.0  1.0   0.0    9.0  2.0  
1  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
2  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
3  0.0  1.0  0.0  0.0  0.0   0.0    6.0  1.0  
4  0.0  0.0  0.0  0.0  0.0   0.0    2.0  1.0  

[5 rows x 35 columns]

In [6]:
df.columns

Index(['LBE', 'LB', 'AC', 'FM', 'UC', 'ASTV', 'MSTV', 'ALTV', 'MLTV', 'DL',
       'DS', 'DP', 'DR', 'Width', 'Min', 'Max', 'Nmax', 'Nzeros', 'Mode',
       'Mean', 'Median', 'Variance', 'Tendency', 'A', 'B', 'C', 'D', 'E', 'AD',
       'DE', 'LD', 'FS', 'SUSP', 'CLASS', 'NSP'],
      dtype='object')

In [7]:
df.shape

(2129, 35)

In [8]:
df.isnull().sum()

LBE         3
LB          3
AC          3
FM          2
UC          2
ASTV        2
MSTV        2
ALTV        2
MLTV        2
DL          1
DS          1
DP          1
DR          1
Width       3
Min         3
Max         3
Nmax        3
Nzeros      3
Mode        3
Mean        3
Median      3
Variance    3
Tendency    3
A           3
B           3
C           3
D           3
E           3
AD          3
DE          3
LD          3
FS          3
SUSP        3
CLASS       3
NSP         3
dtype: int64

In [9]:
df=df.dropna()

In [10]:
df.isnull().sum()

LBE         0
LB          0
AC          0
FM          0
UC          0
ASTV        0
MSTV        0
ALTV        0
MLTV        0
DL          0
DS          0
DP          0
DR          0
Width       0
Min         0
Max         0
Nmax        0
Nzeros      0
Mode        0
Mean        0
Median      0
Variance    0
Tendency    0
A           0
B           0
C           0
D           0
E           0
AD          0
DE          0
LD          0
FS          0
SUSP        0
CLASS       0
NSP         0
dtype: int64

In [11]:
df.dtypes

LBE         float64
LB          float64
AC          float64
FM          float64
UC          float64
ASTV        float64
MSTV        float64
ALTV        float64
MLTV        float64
DL          float64
DS          float64
DP          float64
DR          float64
Width       float64
Min         float64
Max         float64
Nmax        float64
Nzeros      float64
Mode        float64
Mean        float64
Median      float64
Variance    float64
Tendency    float64
A           float64
B           float64
C           float64
D           float64
E           float64
AD          float64
DE          float64
LD          float64
FS          float64
SUSP        float64
CLASS       float64
NSP         float64
dtype: object

In [12]:
X=df[['LBE', 'LB', 'AC', 'FM', 'UC', 'DL',
       'DS', 'DP', 'DR']]
Y=df[["NSP"]]

## Peforming the scaling

In [13]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
Scaler=StandardScaler()
X=Scaler.fit_transform(X)


In [14]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)

## Classifiying the NSP into, Normal=1; Suspect=2; Pathologic=3

### CHecking for appropriate values of gamma

In [15]:
from sklearn.svm import SVC

svm_clf=SVC(kernel="poly",degree=6,coef0=5,gamma=0.1)
svm_clf=svm_clf.fit(X_train,y_train)
y_pred=svm_clf.predict(X_test)


## Calculating different metrics

In [16]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score, confusion_matrix

In [17]:
print(confusion_matrix(y_test,y_pred))

[[470  20   6]
 [ 29  62  10]
 [  8   5  28]]


In [18]:
f1_score(y_test,y_pred,average='weighted')

0.8753514883881671

In [19]:

accuracy_score(y_test,y_pred)

0.877742946708464

In [20]:
precision_score(y_test,y_pred,average='weighted')

0.8744054575648664

In [21]:
recall_score(y_test,y_pred,average="weighted")

0.877742946708464

# Decision Tree Classifier

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
tree_clf=DecisionTreeClassifier(min_samples_split=6, min_samples_leaf=4, max_depth=6, )
tree_clf=tree_clf.fit(X_train,y_train)
y_pred=tree_clf.predict(X_test)

In [24]:
accuracy_score(y_test,y_pred)

0.8683385579937304

In [25]:
recall_score(y_test,y_pred,average="weighted")

0.8683385579937304

In [26]:
precision_score(y_test,y_pred,average='weighted')

0.8603398399877494

In [27]:
from sklearn.tree import export_graphviz
export_graphviz(
tree_clf, out_file="tree.dot",
feature_names=['LBE', 'LB', 'AC', 'FM', 'UC', 'DL',
       'DS', 'DP', 'DR'],
class_names="NSP",
rounded=True,
filled=True)

In [28]:
from subprocess import check_call
check_call(['dot','-Tpng','tree.dot','-o','tree.png'])

0

# Using the ensemble technique

In [29]:
from sklearn.ensemble import VotingClassifier, RandomForestClassifier

In [30]:
svm_clf=SVC(kernel="poly",degree=6,coef0=5,gamma=0.1,probability=True)
decision_tree=DecisionTreeClassifier(min_samples_split=6, min_samples_leaf=4, max_depth=6)
rnd_clf=RandomForestClassifier()
voting_clf=VotingClassifier(estimators=[("svm",svm_clf),('rf',rnd_clf),("decision_tree",decision_tree)],voting="hard")

In [31]:
voting_clf.fit(X_train,y_train)

VotingClassifier(estimators=[('svm',
                              SVC(C=1.0, break_ties=False, cache_size=200,
                                  class_weight=None, coef0=5,
                                  decision_function_shape='ovr', degree=6,
                                  gamma=0.1, kernel='poly', max_iter=-1,
                                  probability=True, random_state=None,
                                  shrinking=True, tol=0.001, verbose=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     ma...
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
              

In [32]:
for clf in (rnd_clf, svm_clf,decision_tree, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

RandomForestClassifier 0.8699059561128527
SVC 0.877742946708464
DecisionTreeClassifier 0.8683385579937304
VotingClassifier 0.8840125391849529


## As, we can observe that there is a slight increase in the overall acuracy while using the ensemble model.

In [33]:
from sklearn.ensemble import BaggingClassifier

In [34]:
bag_clf=BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,n_jobs=-1,max_samples=100, bootstrap=True)

In [35]:
bag_clf.fit(X_train,y_train)
y_pred=bag_clf.predict(X_test)

In [36]:
print(accuracy_score(y_test,y_pred))

0.8636363636363636


In [37]:
##This accuracy is better than our previous decision tree model
##Therefore, we will again call ensemble technique.

In [38]:
voting_clf=VotingClassifier(estimators=[("svm",svm_clf),('rf',rnd_clf),("bagging_clf",bag_clf)],voting="hard")

In [39]:
for clf in (rnd_clf, svm_clf,bag_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

RandomForestClassifier 0.8699059561128527
SVC 0.877742946708464
BaggingClassifier 0.8683385579937304
VotingClassifier 0.8887147335423198


In [40]:
##Using trial and hit method, and performing out-of-box evaluation
##Since a predictor never sees the oob instances during training, it can be evaluated on these instances,
##without the need for a separate validation set or cross-validation. You can evaluate the ensemble itself by
##averaging out the oob evaluations of each predictor.

In [41]:
bag_clf=BaggingClassifier(DecisionTreeClassifier(),n_estimators=500,n_jobs=-1,max_samples=100, bootstrap=True,oob_score=True)
bag_clf.fit(X_train,y_train)
y_pred=bag_clf.predict(X_test)
print(bag_clf.oob_score_)
print(accuracy_score(y_test,y_pred))

0.8602150537634409
0.8699059561128527


# Applying the ADAboost 

In [42]:
from sklearn.ensemble import AdaBoostClassifier

In [43]:
ada_clf=AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=1000,learning_rate=0.1)

In [44]:
ada_clf.fit(X_train,y_train)
y_pred=ada_clf.predict(X_test)

In [45]:
print(accuracy_score(y_test,y_pred))

0.8620689655172413


# Applying XGBoost

In [46]:
from xgboost import XGBClassifier
xgb_clf=XGBClassifier(learning_rate=0.001)
xgb_clf.fit(X_train,y_train)
y_pred=xgb_clf.predict(X_test)

In [47]:
print(accuracy_score(y_test,y_pred))

0.8824451410658307


In [48]:
voting_clf=VotingClassifier(estimators=[("svm",svm_clf),("xgb_clf",xgb_clf)],voting="hard")


In [49]:
for clf in (svm_clf,xgb_clf, voting_clf):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__, accuracy_score(y_test, y_pred))

SVC 0.877742946708464
XGBClassifier 0.8824451410658307
VotingClassifier 0.8808777429467085
